### ISSUE TITLE
Domaine Natalia

### ISSUE THREAD

**Issue by arthaud-proust** [les-voix-errantes-de-kyiv/5-natalia#1]
# Configuration du sous domaine de votre projet

- [x] Ajoutez "natalia.les-voix-errantes-de-kyiv.fr" en tant que nom de domaine sur votre hébergeur (vercel, netlify, etc)
- [ ] **Répondez ci-dessous quel hébergeur vous utilisez pour que je fasse pointer le domaine dessus.**

Merci !
Dispo pour toute question

**Comment by arthaud-proust** [comment]
Hello,
Vous pouvez plutôt mettre le nom de domaine `catalina.les-voix-errantes-de-kyiv.fr` dans votre hébergeur.

**Comment by LucasFrd33** [comment]
vercel
